port: 5233
freeze-timeout: 10
master: false
storage:
  name: postgresql
  driverPath: ./drivers/storage_driver_stub.so
  options:
    port: 5432
    host: 127.0.0.1
    username: admin
    password: qwerty
    database: scheduler
channels:
  tcp-client:
    name: tcp-client
    driverPath: ./drivers/channel_driver_stub.so
    options:
      host: 127.0.0.1
      port: 4444
      username: liar233
      password: qwerty
